name: Build iosApp
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Cancel any current or previous job from the same PR
concurrency:
  group: ios-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0.1'
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Build iOS app
        run: |
          xcodebuild -allowProvisioningUpdates \
            -workspace iosApp/iosApp.xcodeproj/project.xcworkspace \
            -configuration Debug \
            -scheme iosApp \
            -sdk iphonesimulator \
            || true  # Continue even if build fails

      - name: Upload XCode Result Bundle
        if: always()  # This ensures the step runs even if previous steps fail
        uses: actions/upload-artifact@v3
        with:
          name: xcode-result-bundle
          path: |
            /var/folders/g6/rgtlsw6n123b0gt5483s5_cm0000gn/T/ResultBundle_*.xcresult
            iosApp/iosApp.xcodeproj/project.xcworkspace
          retention-days: 5