name: iOS Build

on:
  push:
    branches: [ "update-ci-pipeline" ]
  pull_request:
    branches: [ "kmp-migration" ]

jobs:
  build:
    runs-on: macos-14 # Latest macOS runner with Xcode 15.x

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'gradle'

      - name: Install xcode-install
        run: |
          gem install xcode-install

      - name: Select latest Xcode
        run: |
          LATEST_XCODE="$(ls -t /Applications/ | grep "Xcode" | head -n 1)"
          echo "Using Xcode: $LATEST_XCODE"
          sudo xcode-select -s "/Applications/$LATEST_XCODE"

      - name: Show Xcode version
        run: xcodebuild -version

      - name: List available simulators
        run: xcrun simctl list devices

      - name: Build iOS app
        run: |
          xcodebuild clean build \
            -workspace iosApp/iosApp.xcodeproj/project.xcworkspace \
            -scheme iosApp \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            CODE_SIGNING_ALLOWED=NO \
            ONLY_ACTIVE_ARCH=YES