name: Build iosApp
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Cancel any current or previous job from the same PR
concurrency:
  group: ios-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0.1'
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Build iOS app
        id: build
        continue-on-error: true
        run: |
          xcodebuild -allowProvisioningUpdates -workspace iosApp/iosApp.xcodeproj/project.xcworkspace -configuration Debug -scheme iosApp -sdk iphonesimulator | tee xcodebuild.log
        env:
          RESULT_BUNDLE_PATH: "/var/folders/g6/rgtlsw6n123b0gt5483s5_cm0000gn/T/*.xcresult"

      # Upload the `.xcresult` file as an artifact
      - name: Upload Result Bundle
        if: failure() && steps.build.outcome == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: xcresult-bundle
          path: ${{ env.RESULT_BUNDLE_PATH }}
          retention-days: 7 # Retain for 7 days (adjust as needed)