name: iOS Build

on:
  push:
    branches: [ "update-ci-pipeline" ]
  pull_request:
    branches: [ "kmp-migration" ]


jobs:
  build:
    runs-on: macos-14 # Latest macOS runner with Xcode 16.x
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Build iOS app
        run: xcodebuild -allowProvisioningUpdates -workspace iosApp/iosApp.xcodeproj/project.xcworkspace -configuration Debug -scheme iosApp -sdk iphoneos -destination name='iPhone 15 Pro Max' build
